'use client';
import {useEffect,useState} from 'react';
import {Rocket,RefreshCw,Terminal,RotateCcw,ExternalLink,Plus} from 'lucide-react';
import type {Content} from '../lib/content';
import type {DeploymentJob} from '../lib/deployment';
import {api} from '../lib/client';
type Status={connection:{configured:boolean;url:string};application:{name:string;status:string;url:string;branch:string;commit:string}|null;jobs:DeploymentJob[];images:{tag:string;createdAt:string;current:boolean}[];warnings?:string[]};
const labels:Record<string,string>={created:'应用已创建',submitting:'等待服务响应',queued:'构建已排队',running:'构建中',finished:'部署完成',failed:'失败或已结束跟踪',unknown:'需要核对',cancelled:'已取消'};
export default function DeploymentPanel({content,ensureSaved,notify,onSaved,onLinked}:{onLinked:(content:Content)=>void;content:Content;ensureSaved:()=>Promise<Content|null>;notify:(message:string)=>void;onSaved:()=>void}){
 const [status,setStatus]=useState<Status|null>(null),[busy,setBusy]=useState(false),[logs,setLogs]=useState<string|null>(null),[creating,setCreating]=useState(false),[form,setForm]=useState({projectUuid:'',serverUuid:'',environment:'production',branch:'main',buildPack:'nixpacks',port:3000,baseDirectory:'/',buildCommand:'',startCommand:''}),[rollback,setRollback]=useState('');
 async function refresh(){if(!content.id)return;try{setStatus(await api('/api/deployments?contentId='+content.id));}catch(e){notify((e as Error).message);}}
 useEffect(()=>{void refresh();},[content.id,content.deploymentUuid]);
 async function run(action:'deploy'|'create'|'rollback'){
  setBusy(true);try{const saved=await ensureSaved();if(!saved)return;const result=await api('/api/deployments',{method:'POST',body:JSON.stringify({contentId:saved.id,requestId:crypto.randomUUID(),action,commit:rollback,...form})});notify(result.item.data.message);if(result.content)onLinked(result.content);setCreating(false);onSaved();await refresh();}catch(e){notify((e as Error).message);await refresh();}finally{setBusy(false);}
 }
 async function showLogs(){try{setLogs((await api('/api/deployments?contentId='+content.id+'&mode=logs')).logs);}catch(e){notify((e as Error).message);}}
 async function resolve(job:DeploymentJob){try{await api('/api/deployments',{method:'PATCH',body:JSON.stringify({contentId:content.id,id:job.id})});notify('已结束本站跟踪；服务上的应用和任务继续保留');await refresh();}catch(e){notify((e as Error).message);}}
 const active=status?.jobs.some(j=>['queued','running','submitting','unknown'].includes(j.status));
 return <section className="deployment-panel"><div className="section-heading"><h3><Rocket size={18}/>项目工作台</h3><button className="text-button" disabled={busy||!content.id} onClick={()=>void refresh()}><RefreshCw size={13}/>刷新状态</button></div>{!content.id?<p className="muted">先保存作品，再关联或创建运行环境。</p>:!status?.connection.configured?<div className="deployment-empty"><Rocket size={25}/><div><strong>连接自己的项目运行环境</strong><p>在“设置 → 项目运行环境”连接 Coolify 后，可以从 GitHub 创建应用、部署和查看日志。</p></div></div>:<>
 <div className="deployment-summary"><div><span className="eyebrow">{status.connection.url}</span><strong>{status.application?.name||'尚未关联应用'}</strong><small>{status.application?.status||'填写已有应用标识，或从公开仓库新建应用'}</small></div><div className="deployment-actions">{status.application?.url&&<a className="button" href={status.application.url} target="_blank" rel="noreferrer">在线访问<ExternalLink size={13}/></a>}{content.deploymentUuid?<><button className="button" disabled={busy} onClick={()=>void showLogs()}><Terminal size={14}/>运行日志</button><button className="button primary" disabled={busy||active} onClick={()=>void run('deploy')}><Rocket size={14}/>部署最新代码</button></>:<button className="button" onClick={()=>setCreating(!creating)}><Plus size={14}/>从 GitHub 创建应用</button>}</div></div>
 {creating&&<div className="deployment-create"><h4>为这个作品创建应用</h4><p className="muted">使用作品档案中的公开 GitHub 仓库。创建后先到 Coolify 配置该项目需要的环境变量，再执行首次部署。</p><div className="project-fields">{[['projectUuid','Coolify 项目标识'],['serverUuid','Coolify 服务器标识'],['environment','环境名称'],['branch','Git 分支'],['baseDirectory','项目目录'],['buildCommand','构建命令（可选）'],['startCommand','启动命令（可选）']].map(([key,label])=><label key={key}>{label}<input value={form[key as keyof typeof form]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>构建方式<select value={form.buildPack} onChange={e=>setForm({...form,buildPack:e.target.value})}><option value="nixpacks">自动识别应用</option><option value="static">静态项目</option><option value="dockerfile">Dockerfile</option></select></label><label>服务端口<input type="number" min="1" max="65535" value={form.port} onChange={e=>setForm({...form,port:Number(e.target.value)})}/></label></div><button className="button primary" disabled={busy||active||!content.github||!form.projectUuid||!form.serverUuid} onClick={()=>void run('create')}>创建并关联</button></div>}
 {status.images.length>0&&<div className="rollback-form"><label>保留的历史镜像<select value={rollback} onChange={e=>setRollback(e.target.value)}><option value="">选择回退版本</option>{status.images.filter(i=>!i.current).map(i=><option key={i.tag} value={i.tag}>{i.tag} {i.createdAt}</option>)}</select></label><button className="button" disabled={!rollback||busy||active} onClick={()=>void run('rollback')}><RotateCcw size={14}/>回退代码版本</button><p className="muted">回退镜像保留当前数据库和媒体，不会恢复历史数据。</p></div>}
 {status.warnings?.map((w,i)=><p className="muted" key={i}>{w}</p>)}
 {status.jobs.map(j=><div className="job-row" key={j.id}><div><strong>{j.data.action==='create'?'创建应用':j.data.action==='rollback'?'版本回退':'代码部署'}</strong><small>{new Date(j.createdAt).toLocaleString('zh-CN')} {j.data.commit&&' · '+j.data.commit.slice(0,12)}</small><p>{j.data.message}</p>{j.data.applicationUuid&&<small>应用标识：{j.data.applicationUuid}</small>}</div><span className={`status ${j.status==='finished'||j.status==='created'?'published':''}`}>{labels[j.status]||j.status}</span>{j.status==='unknown'&&<button className="text-button" onClick={()=>void resolve(j)}>已在服务核对，结束跟踪</button>}</div>)}
 </>}{logs!==null&&<div className="deployment-logs"><div className="section-heading"><h4>最近 100 行运行日志</h4><button className="text-button" onClick={()=>setLogs(null)}>关闭</button></div><pre>{logs||'目前没有返回日志'}</pre></div>}</section>;
}
