'use client';
import {useEffect,useRef,useState} from 'react';
import {Radio,RefreshCw,ExternalLink,Send,CheckCircle2} from 'lucide-react';
import type {Content} from '../lib/content';
import {api} from '../lib/client';
import {platforms,statusLabels,mapAccountResult,type SyncAccount,type DistributionJob} from '../lib/distribution';
import {detectAccounts,sendToExtension} from '../lib/sync-bridge';
export default function DistributionPanel({items,notify}:{items:Content[];notify:(message:string)=>void}){
 const [accounts,setAccounts]=useState<SyncAccount[]>([]),[detected,setDetected]=useState(false),[checking,setChecking]=useState(false),[selected,setSelected]=useState<string[]>([]),[contentId,setContentId]=useState(''),[jobs,setJobs]=useState<DistributionJob[]>([]),[busy,setBusy]=useState(false),[verify,setVerify]=useState(''),[url,setUrl]=useState('');
 const timers=useRef<ReturnType<typeof setTimeout>[]>([]),active=useRef(false),mounted=useRef(true),queue=useRef(Promise.resolve());
 const articles=items.filter(i=>i.kind==='article'&&i.isPublic&&!i.hasUnpublishedChanges),article=articles.find(i=>i.id===contentId);
 async function refresh(){try{const data=await api('/api/distribution');if(mounted.current)setJobs(data.items);}catch(e){notify((e as Error).message);}}
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;timers.current.forEach(clearTimeout);};},[]);
 async function detect(){setChecking(true);try{setAccounts((await detectAccounts()).filter(a=>platforms.some(p=>p.id===a.type)));setDetected(true);notify('当前浏览器平台账号检测完成');}catch(e){setDetected(false);notify((e as Error).message);}finally{setChecking(false);}}
 async function sync(){if(!article||active.current)return;const chosen=accounts.filter(a=>selected.includes(a.type));if(!chosen.length){notify('先检测并选择已登录的平台');return;}
   active.current=true;setBusy(true);
   const claimed:DistributionJob[]=[];const completed=new Set<string>();
   try{const prepared=await api('/api/distribution',{method:'POST',body:JSON.stringify({contentId:article.id,revision:article.revision,accounts:chosen.map(a=>({platform:a.type,accountId:String(a.uid||a.title),accountTitle:a.title}))})});
    for(const job of prepared.items as DistributionJob[]){if(!['queued','failed','login_expired','needs_input'].includes(job.status))continue;claimed.push((await api('/api/distribution',{method:'PATCH',body:JSON.stringify({id:job.id,action:'start'})})).item);}
    if(!claimed.length){notify('这个版本已有任务；请查看记录，避免重复同步');active.current=false;setBusy(false);await refresh();return;}
    const report=async(id:string,status:string,message:string,url='')=>{const job=claimed.find(j=>j.id===id)!;if(completed.has(id))return;try{await api('/api/distribution',{method:'PATCH',body:JSON.stringify({id,action:'report',attempt:job.data.attempt,status,message,url})});if(status!=='running')completed.add(id);await refresh();}catch(e){notify('扩展结果尚未保存：'+(e as Error).message);}if(completed.size===claimed.length){active.current=false;if(mounted.current)setBusy(false);}};
    sendToExtension(claimed[0].data.payload,chosen.filter(a=>claimed.some(j=>j.platform===a.type)),results=>{queue.current=queue.current.then(async()=>{for(const result of results){const job=claimed.find(j=>j.platform===result.type);if(job){const mapped=mapAccountResult(result);await report(job.id,mapped.status,mapped.message,mapped.url);}}});});
    timers.current.push(setTimeout(()=>{queue.current=queue.current.then(async()=>{for(const job of claimed)if(!completed.has(job.id))await report(job.id,'unknown','五分钟内未收到完整结果，请在平台与扩展中检查；不要直接重试');});},300000));
    await refresh();notify('已开始同步，保持此页面打开以保存扩展返回的结果');
   }catch(e){notify((e as Error).message);for(const job of claimed)try{await api('/api/distribution',{method:'PATCH',body:JSON.stringify({id:job.id,action:'report',attempt:job.data.attempt,status:'unknown',message:'提交后未取得完整结果，请核对扩展任务'})});}catch{}active.current=false;setBusy(false);await refresh();}
 }
 async function requeue(job:DistributionJob){try{await api('/api/distribution',{method:'PATCH',body:JSON.stringify({id:job.id,action:'requeue'})});notify('已重新排队；选择原文章和平台后可再次同步');await refresh();}catch(e){notify((e as Error).message);}}
 async function record(){try{await api('/api/distribution',{method:'PATCH',body:JSON.stringify({id:verify,action:'verify',url})});setVerify('');setUrl('');notify('已记录你核实的正式发布链接');await refresh();}catch(e){notify((e as Error).message);}}
 return <><div className="page-intro"><div><p className="eyebrow">写一次，让更多地方读到</p><h1>多平台分发</h1><p>知乎、掘金、CSDN 和小红书长文草稿。</p></div><button className="button" disabled={checking||busy} onClick={()=>void detect()}><RefreshCw size={16}/>{checking?'检测中…':'检测浏览器连接'}</button></div>
 <section className="distribution-note"><Radio size={24}/><div><strong>{detected?'已检测当前浏览器':'连接你常用的写作平台'}</strong><p>安装文章同步助手扩展，并在同一浏览器登录平台账号。同步完成后，到平台草稿箱检查排版并发布。小红书目前接入长文草稿。</p></div><a className="button" href="https://github.com/wechatsync/Wechatsync" target="_blank" rel="noreferrer">安装扩展<ExternalLink size={14}/></a></section>
 <div className="platform-grid">{platforms.map(p=>{const account=accounts.find(a=>a.type===p.id);return <label className={`platform-card ${selected.includes(p.id)?'selected':''}`} key={p.id}><div className={`platform-symbol ${p.id}`}>{p.name.slice(0,1)}</div><strong>{p.name}</strong><span>{account?account.title:detected?'尚未登录':'等待检测'}</span><input type="checkbox" aria-label={`选择${p.name}`} disabled={!account||busy} checked={selected.includes(p.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,p.id]:s.filter(x=>x!==p.id))}/>{!account&&<a href={p.login} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>打开平台<ExternalLink size={11}/></a>}</label>;})}</div>
 <section className="settings-card distribution-compose"><h2>选择文章</h2><label>已发布且没有待发布修改的文章<select value={contentId} onChange={e=>setContentId(e.target.value)} disabled={busy}><option value="">选择一篇文章</option>{articles.map(item=><option key={item.id} value={item.id}>{item.title} · 版本 {item.revision}</option>)}</select></label><p className="muted">同一文章版本、平台和账号只创建一个任务。失败任务可修正后重试，结果不明时先到平台核对。</p><button className="button primary" disabled={!article||!selected.length||busy} onClick={()=>void sync()}><Send size={16}/>{busy?'同步进行中…':'一键同步所选平台'}</button></section>
 <section className="settings-card"><div className="section-heading"><h2>分发记录</h2><button className="text-button" onClick={()=>void refresh()}>刷新记录</button></div>{jobs.length?jobs.map(job=><div className="job-row" key={job.id}><div><strong>{job.data.title}</strong><small>{platforms.find(p=>p.id===job.platform)?.name} · {job.data.accountTitle} · 版本 {job.data.revision}</small>{job.data.message&&<p>{job.data.message}</p>}</div><span className={`status ${['draft','published'].includes(job.status)?'published':''}`}>{statusLabels[job.status]}</span><div className="job-actions">{job.data.url&&<a href={job.data.url} className="button" target="_blank" rel="noreferrer">{job.status==='published'?'查看发布':'打开草稿'}<ExternalLink size={13}/></a>}{(job.status==='unknown'||(job.status==='running'&&Date.now()-Date.parse(job.updatedAt)>300000))&&<button className="text-button" disabled={busy} onClick={()=>void requeue(job)}>已核对无草稿，重新排队</button>}{job.status!=='published'&&<button className="text-button" onClick={()=>{setVerify(job.id);setUrl('');}}>记录已发布链接</button>}</div></div>):<p className="muted">同步任务和扩展返回的结果会保存在这里。</p>}{verify&&<div className="inline-form"><label>已在平台检查并正式发布的 HTTPS 链接<input value={url} onChange={e=>setUrl(e.target.value)}/></label><button className="button" onClick={()=>void record()}><CheckCircle2 size={15}/>我已核实</button><button className="button subtle" onClick={()=>setVerify('')}>取消</button></div>}</section></>;
}
