'use client';
import { useEffect,useRef,useState } from 'react';
import { Upload,Copy,Image as ImageIcon,Film,Search } from 'lucide-react';
import { api,upload } from '../lib/client';
import type { MediaItem } from '../lib/media';
export default function MediaLibrary({notify}:{notify:(message:string)=>void}){
  const [items,setItems]=useState<MediaItem[]>([]),[query,setQuery]=useState(''),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
  async function refresh(){try{setItems((await api('/api/media')).items);}catch(e){notify((e as Error).message);}}
  useEffect(()=>{void refresh();},[]);
  async function add(files:FileList|null){if(!files)return;setBusy(true);try{for(const file of Array.from(files)){await upload(file);}await refresh();notify('媒体已保存到素材库');}catch(e){notify((e as Error).message);}finally{setBusy(false);if(input.current)input.current.value='';}}
  return <><div className="page-intro"><div><p className="eyebrow">创作的素材，都在这里</p><h1>媒体库</h1><p>图片与视频可以在文章编辑器中直接插入。</p></div><button className="button primary" disabled={busy} onClick={()=>input.current?.click()}><Upload size={17}/>{busy?'正在上传':'上传素材'}</button><input ref={input} hidden type="file" multiple accept="image/png,image/jpeg,image/webp,image/gif,video/mp4,video/webm" onChange={e=>void add(e.target.files)}/></div><div className="media-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void add(e.dataTransfer.files);}}><Upload size={25}/><strong>把文件拖到这里</strong><span>图片最多 10 MB，视频最多 25 MB。大型视频可使用平台嵌入链接。</span></div><div className="section-heading"><span className="muted">{items.length} 个素材 · {(items.reduce((sum,item)=>sum+item.size,0)/1024/1024).toFixed(1)} MB</span><label className="search-field"><Search size={16}/><input aria-label="搜索媒体" placeholder="搜索文件名" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>{items.length?<div className="media-grid">{items.filter(item=>item.name.toLowerCase().includes(query.toLowerCase())).map(item=><div className="media-card" key={item.id}><div className="media-preview">{item.mime.startsWith('image/')?<img src={item.url} alt={item.name} loading="lazy"/>:<video src={item.url} controls preload="metadata"/>}</div><div className="media-info"><span>{item.mime.startsWith('image/')?<ImageIcon size={15}/>:<Film size={15}/>}</span><div><strong>{item.name}</strong><small>{(item.size/1024/1024).toFixed(2)} MB</small></div><button className="icon-btn" aria-label="复制媒体地址" onClick={async()=>{try{await navigator.clipboard.writeText(item.url);notify('已复制可插入文章的媒体地址');}catch{notify(`媒体地址：${item.url}`);}}}><Copy size={16}/></button></div></div>)}</div>:<div className="empty-state"><ImageIcon size={30}/><h3>为你的文章加一点画面</h3><p>上传后可以从媒体库选择，或直接粘贴到编辑器。</p></div>}</>;
}
