'use client';
import { useEffect,useState } from 'react';
import { SlidersHorizontal,Pin,Save } from 'lucide-react';
import { api } from '../lib/client';
import { recommend,normaliseOptions,defaultRecommendation,type RecommendationOptions } from '../lib/recommendation';
import type { Content } from '../lib/content';
const labels={editorial:'编辑精选',completeness:'内容完整度',freshness:'新鲜度',engagement:'阅读反馈',relevance:'主题相关度'};
export default function RecommendationPanel({items,notify}:{items:Content[];notify:(text:string)=>void}){
  const [options,setOptions]=useState<RecommendationOptions>(defaultRecommendation),[saving,setSaving]=useState(false);
  useEffect(()=>{api('/api/settings').then(data=>setOptions(normaliseOptions(data.recommendation))).catch(e=>notify(e.message));},[]);
  const live=items.filter(i=>i.isPublic).map(item=>({...item,status:'published'})),preview=recommend(live,options,{seed:'admin-preview',count:6});
  function pin(id:string){setOptions(current=>({...current,pins:current.pins.includes(id)?current.pins.filter(p=>p!==id):[...current.pins,id]}));}
  async function save(){setSaving(true);try{const normal=normaliseOptions(options);await api('/api/settings',{method:'PUT',body:JSON.stringify({recommendation:normal})});setOptions(normal);notify('推荐规则已保存，前台会按新规则读取');}catch(e){notify((e as Error).message);}finally{setSaving(false);}}
  return <><div className="page-intro"><div><p className="eyebrow">把想展示的创作，放到合适的位置</p><h1>首页推荐</h1><p>文章和作品混合排序；置顶优先，草稿与回收站内容不会进入推荐。</p></div><button className="button primary" onClick={()=>void save()} disabled={saving}><Save size={16}/>保存规则</button></div><div className="recommendation-layout"><section className="settings-card"><div className="section-heading"><h2><SlidersHorizontal size={18}/>推荐权重</h2><button className="text-button" onClick={()=>setOptions(defaultRecommendation)}>恢复默认</button></div>{Object.entries(labels).map(([key,label])=><label className="weight-row" key={key}><div><span>{label}</span><strong>{Math.round(options.weights[key as keyof typeof labels]*100)}%</strong></div><input type="range" min="0" max="100" value={options.weights[key as keyof typeof labels]*100} onChange={e=>setOptions(current=>({...current,weights:{...current.weights,[key]:Number(e.target.value)/100}}))}/></label>)}<p className="muted">保存时自动归一化。阅读数据不足时使用先验值，保持新站内容可见。</p><label className="weight-row"><div><span>探索比例</span><strong>{Math.round(options.exploration*100)}%</strong></div><input type="range" min="0" max="20" value={options.exploration*100} onChange={e=>setOptions(current=>({...current,exploration:Number(e.target.value)/100}))}/></label><p className="muted">同一访问会话保持顺序稳定，适量探索其他主题。</p></section><section className="settings-card"><h2>推荐结果预览</h2>{preview.length?preview.map((item,index)=><div className="recommend-row" key={item.id}><span className="rank-number">{index+1}</span><div><strong>{item.title}</strong><small>{item.kind==='article'?'文章':'作品'} · {item.reason} {item.coldStart?'· 冷启动':''}</small></div><span>{item.score.toFixed(3)}</span></div>):<div className="empty-state"><h3>先发布一项内容</h3><p>这里会显示排序与每项内容的推荐理由。</p></div>}</section></div><section className="settings-card"><h2><Pin size={18}/>手动置顶</h2><p className="muted">按选入的顺序优先展示，取消后会恢复算法排序。</p><div className="pin-list">{live.map(item=><button key={item.id} aria-pressed={options.pins.includes(item.id)} className={`pin-option ${options.pins.includes(item.id)?'pinned':''}`} onClick={()=>pin(item.id)}><Pin size={15}/>{item.title}{options.pins.includes(item.id)&&<small>第 {options.pins.indexOf(item.id)+1} 位</small>}</button>)}</div></section></>;
}
