'use client';
import { useEffect, useRef, useState } from 'react';
import { LayoutDashboard, PenLine, FolderOpen, Images, Radio, SlidersHorizontal, Settings, Plus, ArrowUpRight, Trash2, RotateCcw, Search, Sparkles } from 'lucide-react';
import Editor, { api, blankContent } from './Editor';
import type { Content } from '../lib/content';
import MediaLibrary from './MediaLibrary';
import ImportExport from './ImportExport';
import RecommendationPanel from './RecommendationPanel';
import SettingsPanel from './SettingsPanel';
import DistributionPanel from './DistributionPanel';
const navigation=[['overview','概览',LayoutDashboard],['articles','文章',PenLine],['projects','作品与部署',FolderOpen],['media','媒体库',Images],['distribution','多平台分发',Radio],['recommendation','首页推荐',SlidersHorizontal],['settings','设置',Settings]] as const;
export default function Studio({name,webUrl}:{name:string;webUrl:string}) {
  const [section,setSection]=useState('overview'),[items,setItems]=useState<Content[]>([]),[editor,setEditor]=useState<Content|null>(null),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[trash,setTrash]=useState(false);
  const leave=useRef<(()=>Promise<boolean>)|null>(null),notify=(text:string)=>setMessage(text);
  async function refresh(){try{setItems((await api(`/api/content${trash?'?trash=1':''}`)).items);}catch(e){notify((e as Error).message);}finally{setLoading(false);}}
  useEffect(()=>{void refresh();},[trash]);
  const articles=items.filter(i=>i.kind==='article'),projects=items.filter(i=>i.kind==='project');
  const listed=items.filter(i=>i.kind===(section==='projects'?'project':'article')&&`${i.title} ${i.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  async function navigate(key:string){if(editor&&leave.current&&!await leave.current())return;setEditor(null);setSection(key);setQuery('');}
  async function remove(item:Content){try{await api(`/api/content/${item.id}`,{method:'DELETE'});notify('已移到回收站，可以恢复');await refresh();}catch(e){notify((e as Error).message);}}
  async function restore(item:Content){try{await api(`/api/content/${item.id}`,{method:'PATCH',body:JSON.stringify({action:'restore_trash',expectedRevision:item.revision})});notify('已恢复');await refresh();}catch(e){notify((e as Error).message);}}
  function open(kind:'article'|'project'){setEditor(blankContent(kind));setSection(kind==='article'?'articles':'projects');}
  return <div className="studio-shell"><aside className="sidebar"><a className="studio-brand" href="/"><span className="brand-mark">✳</span><div>创作桌<small>管理台</small></div></a><div className="workspace-name"><span className="avatar">橘</span><div>{name}<small>个人工作空间</small></div><span className="online-dot"/></div><nav aria-label="管理导航">{navigation.map(([key,label,Icon])=><button key={key} className={section===key?'active':''} onClick={()=>void navigate(key)}><Icon size={18}/><span>{label}</span>{key==='articles'&&<small>{articles.length}</small>}</button>)}</nav><div className="sidebar-bottom"><a href={webUrl} target="_blank" rel="noreferrer">查看我的网站<ArrowUpRight size={16}/></a><p>每一个想法，都有它的位置。</p><span className="private-badge">仅本人可访问</span></div></aside>
  <main className="studio-main"><header className="studio-header"><div className="breadcrumb">工作空间<span>/</span>{navigation.find(n=>n[0]===section)?.[1]}</div><a className="button subtle" href={webUrl} target="_blank" rel="noreferrer">打开前台<ArrowUpRight size={16}/></a></header>{message&&<div className="notice" role="status"><span>{message}</span><button aria-label="关闭提示" onClick={()=>setMessage('')}>×</button></div>}
  {editor?<Editor key={editor.id||'new'} initial={editor} onBack={()=>setEditor(null)} onSaved={()=>void refresh()} notify={notify} beforeLeaveRef={leave}/>:<div className="studio-content">
  {section==='overview'&&<><div className="page-intro"><div><p className="eyebrow">创作从这里继续</p><h1>你好，{name} <span className="hand-wave">✳</span></h1><p>写下新的想法，看看正在生长的作品。</p></div><button className="button primary" onClick={()=>open('article')}><Plus size={18}/>开始写作</button></div><div className="overview-stats">{[['文章',articles.length],['已发布',items.filter(i=>i.isPublic).length],['作品',projects.length],['草稿',items.filter(i=>!i.publicAt).length]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><section className="welcome-note"><div className="note-star">✳</div><div><h2>你的下一件作品，<br/>从一个小小的想法开始。</h2><p>用 Markdown 把过程记下来，<br/>让文章和作品一起成为你的个人档案。</p></div><button className="button" onClick={()=>open('project')}>添加作品<Plus size={16}/></button></section><section><div className="section-heading"><h2>最近的创作</h2><button className="text-button" onClick={()=>setSection('articles')}>查看全部</button></div>{items.length?<div className="content-list">{items.slice(0,5).map(item=><button className="recent-row" key={item.id} onClick={()=>{setEditor(item);setSection(item.kind==='article'?'articles':'projects');}}><span className={`content-icon ${item.accent}`}>{item.kind==='article'?<PenLine size={19}/>:<FolderOpen size={19}/>}</span><div><strong>{item.title}</strong><small>{item.kind==='article'?'文章':'作品'} · {new Date(item.updatedAt).toLocaleDateString('zh-CN')}</small></div><span className={`status ${item.isPublic?'published':''}`}>{item.isPublic?'已发布':item.status==='scheduled'?'待定时发布':'草稿'}</span><ArrowUpRight size={17}/></button>)}</div>:<div className="empty-state"><PenLine size={30}/><h3>第一篇文章，等你来写</h3><p>写作、作品与媒体会保存到你的内容库。</p><button className="button" onClick={()=>open('article')}>新建文章</button></div>}</section></>}
  {(section==='articles'||section==='projects')&&<><div className="page-intro"><div><p className="eyebrow">{section==='articles'?'文字也是一种作品':'让作品拥有自己的舞台'}</p><h1>{section==='articles'?'文章':'作品与部署'}</h1><p>{section==='articles'?'保存思考的过程，也保存每一次修改。':'管理项目档案、在线演示和部署版本。'}</p></div><button className="button primary" onClick={()=>open(section==='articles'?'article':'project')}><Plus size={18}/>新建{section==='articles'?'文章':'作品'}</button></div><ImportExport notify={notify} onImported={()=>void refresh()}/><div className="list-toolbar"><label className="search-field"><Search size={17}/><input aria-label="搜索内容" placeholder="搜索标题或标签" value={query} onChange={e=>setQuery(e.target.value)}/></label><button className={`button ${trash?'selected':''}`} onClick={()=>setTrash(!trash)}><Trash2 size={16}/>{trash?'返回内容':'回收站'}</button></div>{loading?<p className="muted">正在读取内容…</p>:listed.length?<div className="content-table"><div className="table-header"><span>标题</span><span>状态</span><span>最近修改</span><span>操作</span></div>{listed.map(item=><div className="table-row" key={item.id}><button className="title-cell" onClick={()=>setEditor(item)}><span className={`content-icon ${item.accent}`}>{item.kind==='article'?<PenLine size={18}/>:<FolderOpen size={18}/>}</span><div><strong>{item.title}</strong><small>{item.tags.join(' / ')||'尚未设置标签'}</small></div></button><span className={`status ${item.isPublic?'published':''}`}>{item.isPublic?(item.hasUnpublishedChanges?'有新修改':'已发布'):item.status==='scheduled'?'定时发布':'草稿'}</span><time>{new Date(item.updatedAt).toLocaleDateString('zh-CN')}</time><button className="icon-btn" aria-label={trash?'恢复':'移到回收站'} onClick={()=>void(trash?restore(item):remove(item))}>{trash?<RotateCcw size={17}/>:<Trash2 size={17}/>}</button></div>)}</div>:<div className="empty-state"><FolderOpen size={30}/><h3>{trash?'回收站是空的':'这里会收下你的创作'}</h3><p>{trash?'移入回收站的内容可以恢复。':'新建内容后，可以随时保存、预览和发布。'}</p></div>}</>}
  {section==='media'&&<MediaLibrary notify={notify}/>}
  {section==='recommendation'&&<RecommendationPanel items={items} notify={notify}/>}
  {section==='settings'&&<SettingsPanel notify={notify} onImported={()=>void refresh()}/>}
  {section==='distribution'&&<DistributionPanel items={items} notify={notify}/>}
  </div>}</main></div>;
}
