import { ArrowUpRight } from 'lucide-react';
import type { Publication } from '../lib/public-data';
import { readingMinutes } from '../lib/markdown';
export function ProjectArt({item}:{item:{cover?:unknown;accent?:unknown;title?:unknown;slug?:unknown}}){
  if(typeof item.cover==='string'&&item.cover)return <img className="project-cover" src={item.cover} alt={`${item.title} 的作品预览`} loading="lazy"/>;
  return <div className={`project-art ${item.accent??'blue'}`} aria-hidden="true"><div className="art-window"><div className="window-dots"><i/><i/><i/></div><div className="art-layout"><div className="art-sidebar"/><div className="art-content"><b/><span/><span/><div className="art-blocks"><i/><i/><i/></div></div></div></div><span className="art-label">{String(item.title??'一个新想法')}</span><span className="art-flower">✳</span></div>;
}
export function ProjectCard({item}:{item:Publication}){return <a href={`/projects/${encodeURIComponent(item.slug)}`} className="project-card"><div className="project-cover-wrap"><ProjectArt item={item}/><span className="project-open"><ArrowUpRight size={23}/></span></div><div className="project-card-title"><h3>{item.title}</h3><span className={`project-status ${item.projectStatus==='live'?'live':''}`}>{item.demoContent?'内置示例':item.projectStatus==='live'?'已上线':item.projectStatus==='paused'?'暂时暂停':'持续探索'}</span></div><p>{item.excerpt}</p><div className="project-tags">{(item.tech??item.tags).slice(0,4).map(tag=><span key={tag}>{tag}</span>)}</div></a>;}
export function ArticleRow({item}:{item:Publication}){return <a href={`/articles/${encodeURIComponent(item.slug)}`} className="article-row"><div className="article-date"><span>{new Date(item.publicAt??'').toLocaleDateString('zh-CN',{month:'short',day:'numeric'})}</span><small>{readingMinutes(item.markdown)} 分钟阅读</small></div><div className="article-row-body"><div className="article-tagline">{item.tags.slice(0,2).join(' / ')}{item.demoContent&&<span>示例文章</span>}</div><h3>{item.title}</h3><p>{item.excerpt}</p></div><span className="article-arrow"><ArrowUpRight size={22}/></span></a>;}
