'use client';
import { useEffect,useMemo,useState } from 'react';
import { ArrowDown,ArrowUpRight,ArrowRight,PenLine,Sparkles } from 'lucide-react';
import type { Profile,Publication } from '../lib/public-data';
import { recommend,type RecommendationOptions } from '../lib/recommendation';
import { ProjectArt,ProjectCard,ArticleRow } from './Cards';
export default function Home({items,profile,available,options}:{items:Publication[];profile:Profile;available:boolean;options:RecommendationOptions}){
  const [tab,setTab]=useState('all'),[topic,setTopic]=useState(''),[seed,setSeed]=useState('home');
  useEffect(()=>{let session=sessionStorage.getItem('creative-visit');if(!session){session=crypto.randomUUID();sessionStorage.setItem('creative-visit',session);}setSeed(session);},[]);
  const ranked=useMemo(()=>recommend(items,options,{count:6,seed,topics:topic?[topic]:[]}),[items,options,topic,seed]);
  const projects=items.filter(item=>item.kind==='project'),articles=items.filter(item=>item.kind==='article'),topics=Array.from(new Set(items.flatMap(item=>item.tags))).slice(0,8);
  const shown=ranked.filter(item=>tab==='all'||item.kind===tab) as (Publication&{reason:string})[];
  return <>
    <section className="hero"><div className="hero-copy"><div className="hello-line"><span className="little-avatar">{Array.from(profile.name)[0]}</span><span>欢迎来到我的小小创作空间</span><span className="tiny-star">✦</span></div><h1>一些想法，<br/>一些正在发生的<br/><span className="headline-last">创作。</span></h1><p>{profile.tagline}</p><div className="hero-links"><a className="ink-button" href="#creations">逛逛我的作品<ArrowDown size={16}/></a><a className="plain-link" href="/about">认识一下我<ArrowUpRight size={16}/></a></div><div className="hero-footnote"><span className="hand-line"/>慢慢做，也慢慢长大。</div></div>
    <div className="creative-board"><div className="board-halo"/><span className="board-note">keep making things.</span><a className="board-sheet primary-sheet" href={projects[0]?`/projects/${encodeURIComponent(projects[0].slug)}`:'/projects'}><ProjectArt item={projects[0]??{title:'你的下一个作品',accent:'blue'}}/><div className="sheet-caption"><span>{projects[0]?.title??'想法，正在生长'}</span><ArrowUpRight size={19}/></div></a><a className="board-sheet note-sheet" href={articles[0]?`/articles/${encodeURIComponent(articles[0].slug)}`:'/articles'}><span className="paper-tape"/><PenLine size={22}/><p>{articles[0]?.title??'把一个想法\n认真写下来。'}</p><small>{articles[0]?'最近写下的文字':'一页新的空白'}</small><div className="note-lines"><i/><i/><i/></div></a><div className="board-sticker"><span>✳</span><small>想到哪<br/>做到哪</small></div><div className="board-label"><span className="pencil-arrow">↗</span>这张桌子一直在更新</div><div className="board-dots"><i/><i/><i/></div></div></section>
    {!available&&<p className="connection-message" role="status">内容库暂时无法连接，请稍后再来看看。</p>}
    <section id="creations" className="creations"><div className="public-section-title"><div><h2>最近的创作<span className="title-doodle">✳</span></h2><p>写下来的，做出来的，都在这里。</p></div><div className="content-tabs" aria-label="内容类型">{[['all','全部'],['project','作品'],['article','文章']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div></div>
    {topics.length>0&&<div className="topic-pills"><button className={!topic?'selected':''} onClick={()=>setTopic('')}>所有主题</button>{topics.map(tag=><button className={topic===tag?'selected':''} key={tag} onClick={()=>setTopic(topic===tag?'':tag)}>#{tag}</button>)}</div>}
    {shown.length?<div className="mixed-grid">{shown.map(item=><div key={item.id} className={`mixed-item ${item.kind==='article'?'note-item':''}`}>{item.kind==='project'?<ProjectCard item={item}/>:<a href={`/articles/${encodeURIComponent(item.slug)}`} className={`note-card ${item.accent}`}><div className="note-card-meta"><PenLine size={17}/><span>{item.demoContent?'示例文章':item.tags[0]??'随笔'}</span><ArrowUpRight size={17}/></div><h3>{item.title}</h3><p>{item.excerpt}</p><div className="note-card-footer"><time>{new Date(item.publicAt??'').toLocaleDateString('zh-CN',{month:'short',day:'numeric'})}</time><span>阅读全文<ArrowRight size={14}/></span></div></a>}<small className="recommendation-reason"><Sparkles size={11}/>{item.reason}</small></div>)}</div>:<div className="public-empty"><span>✳</span><h3>新的创作，正在路上</h3><p>这里会摆上我的文章和作品。</p></div>}
    </section>
    <section className="notes-section"><div className="public-section-title"><div><h2>写在途中</h2><p>留下过程，想法就有了自己的轮廓。</p></div><a className="plain-link" href="/articles">所有文章<ArrowUpRight size={17}/></a></div>{articles.length?<div className="article-list">{articles.slice(0,3).map(item=><ArticleRow item={item} key={item.id}/>)}</div>:<p className="empty-copy">第一篇文字，很快会出现在这里。</p>}</section>
    <section className="about-strip"><div className="strip-flower">✳</div><div><h2>创作这件事，<br/>我想一直做下去。</h2><p>{profile.bio}</p></div><a className="ink-button" href="/about">关于我<ArrowUpRight size={16}/></a></section>
  </>;
}
